### ISSUE TITLE
Issues with QT

### ISSUE THREAD

**Issue by kendoori** [kapitainsky/RcloneBrowser#1]
Found reference to your new version (thanks for doing this). The browser is useful, and too bad that it hadn't been updated.

Am running Mint 19.2. Here's what is echoed back.

`/usr/bin/rclone-browser: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr/bin/rclone-browser)
`

**Comment by kapitainsky** [comment]
I packaged linux version for Debian (system I am using). I have to admit that software packaging is not something I do often so possible that my deb file is not perfect.

In order to solve your issue I would try first to install Mint qt5 packages (I found this Qt install suggestion here https://forums.linuxmint.com/viewtopic.php?t=278552)

`sudo apt install qt5-default qttools5-dev-tools qttools5-dev`

and if it does not help compile rclone-browser from source - instruction is on Readme page of this repo. It is very straightforward and takes few mins only,

**Comment by kapitainsky** [comment]
I quickly tried myself running mint in VM and looks like compilation is required

**Comment by kapitainsky** [comment]
Now I tested building on mint and all works fine.

Just follow steps from here https://github.com/kapitainsky/RcloneBrowser#build-instructions-for-other-unix-like-systems

and when finished and still in build folder run

`sudo mv ./build/rclone-browser /usr/bin` 

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/15635386/63647860-e5a01080-c759-11e9-8d0d-19b6e08aec3e.png">

**Comment by kapitainsky** [comment]
I will have to have a look how to create deb file compatible with Ubuntu based distros. In the meantime only way is to build it from source.

**Comment by kendoori** [comment]
Thank you! that worked!

**Comment by kendoori** [comment]
Windows version on Windows 10 works too!

**Comment by kapitainsky** [comment]
Looks like Qt is not backward compatible so when I compiled rclone-browser with Qt 5.13 deb file binary does not work with older Qt runtimes. In the meantime I re compiled linux version with older Qt to make sure that it works with main distros used at the moment.
