### ISSUE TITLE
edit a task

### ISSUE THREAD

**Issue by adnoh** [kapitainsky/RcloneBrowser#63]
Hello there,
why can I not edit a task? Like source and destination is disabled on WIN Portable. Bug or feature? Thanks

**Comment by kapitainsky** [comment]
It was design decision long time ago. Plans were to add logging and history and it was easier to assume that source and destination stay the same within specific task. Was it right? I am not sure but it is legacy code and I don’t find it critical to change.

**Comment by MostHated** [comment]
Hey again,  
I would like to add that I feel that, while this may technically be "non-critical", it can certainly end up being a major inconvenience as I have just experienced. Considering that when you hit edit, the box is right there already, it seems unnecessarily restrictive to not allow for editing the path. I needed to do this just a few minutes ago, which was what lead me here once I discovered I was unable to do so. 

I was reorganizing my NAS and changed a few folder names for consistency when I went to change the paths in my tasks and realized I cannot edit them. Not only that, but I also was not able to edit the task file which contained them. I expected it to be a text file containing a command and appropriate arguments similar to when you would select the "copy command to clipboard option", but I see now that, that is not the case. Unfortunately, I now have to delete all of my tasks and their individual rules, settings, and excludes simply because I needed to change a space to an underscore in a folder name.

I can say with certainty that when you have multiple tasks and they have their own configurations, it would be a very welcome adjustment to be able to avoid having to completely remove them and recreate them if I just need to make some slight adjustments to the path. 

Thanks again,
-MH

**Comment by kapitainsky** [comment]
it will be also included in the next release - see #87

**Comment by kapitainsky** [comment]
"Thanks" to quarantine I have a bit of spare time so working on massively improved next version. It is 90% ready. Can't commit to specific date but should roll it out in the next week or two.

**Comment by MostHated** [comment]
Ah, perfect. I do apologize in that case. I had just done a search for the terms when I came across this thread and missed the other one.

As for quarantine, unfortunately, I understand all too well. I was just laid off yesterday so I have been using this time to do maintenance tasks I have been avoiding (such as reorganizing my NAS, lol), and doing updates to some of my projects as well.

**Comment by kapitainsky** [comment]
If you are on windows you can try latest beta from here #93 (link in the first post)

**Comment by MostHated** [comment]
Very good. The machine I am currently working on reconfiguring is indeed Windows, so I will give it a try. 👍

**Comment by MostHated** [comment]
One quick question, if you do not mind. When it comes to optional parameters, which ones take precedence? I had some within the general preferences under Default rclone options, such as --ignore-case --fast-list --checkers 8, but then the task menu has options as well. Do those override any that are set in the default options?

**Comment by kapitainsky** [comment]
Good point I should make it more clear.

so you have in preferences

1. Default rclone options - they will be used for any rclone operation (listing remot,e download, upload etc) - perfect for —fast-list or to ignore invalid remote certificate
2. Default download and upload options - they will be added for all download/upload operations respectively - maybe some exclude or include options here
3. Default mount options - only added for mount operations

then you can add more options using extra option field.


you can always check effective rclone command in jobs - next to cancel button there is “copy rclone command to clipboard"

**Comment by ioogithub** [comment]
This issue is maked as closed however I would also like the ability to edit the source and destination fields. I migrated my rclone to a new install and I copied my tasks.bin file. These two fields changed and because I can't edit the fields I ended up having spend over 1 hour recreating all my jobs by copying and pasting. It was a messy and error prone task.

What could possible be the rational be for restrict the user from editing the task data that he has create?
