### ISSUE TITLE
File transfer keeps counting WHILE transferring

### ISSUE THREAD

**Issue by DankMemeGuy** [kapitainsky/RcloneBrowser#89]
I'm performing a large file transfer (a few million files), the problem is that instead of RClone Browser determining how many files need to be transfered, it started the process while still counting. So for example it said 100,000 files needed to be uploaded, but finished 90,000 so 90% done, however it keeps counting (since the total is actually a few million) so that % figure is never accurate.

I understand this is just an appearance problem, and it's doing something I'd want - start as soon as possible instead of waiting to calculate how many files needed to transfer than transfer, thus getting the job done sooner. However, I'm trying to speed this process up (in terms of opportunity cost and choosing another means of uploading like splitting files, etc), so I don't know how long it will actually take since the numbers are lying to me. 

Surely there must be a solution to count large amount of files without taking a long time and then start the transfer?

**Comment by kapitainsky** [comment]
Rclone Browser is only rclone GUI. It does not do any transfers, calculations on its own. It just sucks rclone generated results. 

You should bring this issue on rclone forum https://forum.rclone.org/

From my understanding it is not just appearance problem. It is question of efficiency. You want your nice stats always 100% correct? Or keep transferring files. Exactly in cases like yours - millions of files - you can’t have both without sacrificing something. Rclone guys made decision to sacrifice accuracy of stats. And this is one reason I keep using rclone:) because it is one of very few tools that can handle millions of files problem.

**Comment by thanamaha2002** [comment]
Try remove `--fast-list` from the option then test it again. If this does not help, you should open the issue on the [official rclone forum.](https://forum.rclone.org/)

**Comment by kapitainsky** [comment]
Rclone, by default, only gets 10,000 files ahead to save on memory.

You can use this config parameter to allow it to get further ahead.

`--max-backlog int           Maximum number of objects in sync or check backlog. (default 10000)`

If that number is bigger than the number of files you have to transfer then you will get accurate transfer stats! Otherwise they will get there eventually.

Source: https://forum.rclone.org/t/progress-shows-incorrect-total-size-to-be-transferred/8686/3?u=kapitainsky
